import { FileImage, Printer, Smartphone, Code } from "lucide-react"

export const categories = [
  { id: "poster", label: "Template Poster", icon: FileImage },
  { id: "social", label: "Template Media Sosial", icon: Smartphone },
  { id: "webcode", label: "Template Web & Source Code", icon: Code },
  { id: "print", label: "Template Cetak", icon: Printer },
]

export const services = {
  poster: [
    {
      title: "Poster Bukber ✨",
      description: "Template undangan buka puasa bersama dengan desain islami yang elegan.",
      descriptionFull: "HALO, SELAMAT DATANG DI FAN DESIGN✨\n\nTemplate ini dirancang khusus untuk Undangan Buka Puasa Bersama dengan sentuhan desain islami yang elegan dan modern. Mudah diedit menggunakan Canva.",
      features: ["Desain memukau", "Hierarki visual rapi", "Format Canva & PSD"],
      priceOriginal: 15000,
      priceDiscount: 10000,
      image: "/ucapan.png", 
      popular: true,
    },
    {
      title: "Poster Energi Terbarukan ✨",
      description: "Template poster edukatif tentang energi terbarukan.",
      descriptionFull: "Temukan keajaiban energi terbarukan dengan template poster edukatif ini. Sempurna untuk tugas sekolah atau kampanye kesadaran lingkungan.",
      features: ["Desain persuasif", "High CTR layouts", "Format Canva & PSD"],
      priceOriginal: 15000,
      priceDiscount: 10000,
      image: "/Poster Seminar.png",
      popular: false,
    },
    {
      title: "Hidup Sehat Gizi Seimbang",
      description: "Template infografis kesehatan tentang pentingnya gizi seimbang.",
      descriptionFull: "Tingkatkan kesadaran akan pola hidup sehat dengan template infografis ini. Visual yang jelas membuat data mudah dipahami oleh audiens.",
      features: ["Infografis elegan", "Tipografi bersih", "Data terstruktur"],
      priceOriginal: 20000,
      priceDiscount: 15000,
      image: "/infografis.jpg", 
      popular: false,
    },
    {
      title: "Kampanye Anti Pergaulan Bebas",
      description: "Template poster kampanye sosial remaja dan pelajar.",
      descriptionFull: "Lawan pergaulan bebas dengan template poster kampanye ini. Desain yang kuat dan inspiratif akan menyampaikan pesan Anda dengan efektif.",
      features: ["Pesan kuat", "Vektor presisi", "Format besar ready"],
      priceOriginal: 20000,
      priceDiscount: 15000,
      image: "/TBC Fiks.png",
      popular: true,
    },
    {
      title: "Poster Event Musik Lokal",
      description: "Template poster konser dan live music bergaya vintage/retro.",
      descriptionFull: "Sempurna untuk mempromosikan gig lokal, band indie, atau festival musik. Mudah diganti warna dan fotonya.",
      features: ["Gaya Retro/Vintage", "Font tipografi tebal", "Warna mencolok"],
      priceOriginal: 25000,
      priceDiscount: 15000,
      image: "/Poster Seminar.png",
      popular: false,
    },
    {
      title: "Poster Lomba 17 Agustus",
      description: "Template poster peringatan kemerdekaan dan perlombaan.",
      descriptionFull: "Semarakkan acara 17 Agustusan di lingkungan Anda dengan poster yang meriah dan penuh semangat nasionalisme.",
      features: ["Tema Merah Putih", "Layout dinamis", "Mudah dikustomisasi"],
      priceOriginal: 15000,
      priceDiscount: 9000,
      image: "/Poster Seminar.png",
      popular: true,
    }
  ],
  social: [
    {
      title: "Instagram Feed Aesthetic",
      description: "Template feed Instagram premium untuk personal branding.",
      descriptionFull: "Tingkatkan engagement dengan template aesthetic untuk Instagram. Termasuk 10 grid layout yang saling menyambung.",
      features: ["Mudah edit di Canva", "Aesthetic grid", "Engagement focused"],
      priceOriginal: 25000,
      priceDiscount: 15000,
      image: "/promosi.png",
      popular: true,
    },
    {
      title: "Microblogging Carousel",
      description: "Template carousel edukasi untuk konten kreator.",
      descriptionFull: "Bagikan ilmu Anda lewat format microblogging yang interaktif. 10 slide carousel siap pakai dengan panduan copywriting.",
      features: ["Carousel format", "High save rate", "Tipografi rapi"],
      priceOriginal: 30000,
      priceDiscount: 20000,
      image: "/flyer.png",
      popular: true,
    },
    {
      title: "Katalog Produk Fashion",
      description: "Template Instagram story untuk showcase produk.",
      descriptionFull: "Promosikan koleksi terbaru pakaian Anda dengan template story elegan yang didesain untuk menonjolkan visual produk.",
      features: ["Story format (9:16)", "Gaya minimalis", "Ruang foto besar"],
      priceOriginal: 20000,
      priceDiscount: 15000,
      image: "/promosi.png",
      popular: false,
    },
    {
      title: "Banner Promo Diskon",
      description: "Template postingan diskon flash sale untuk e-commerce.",
      descriptionFull: "Buat audiens FOMO dengan template flash sale yang mencolok dan persuasif ini.",
      features: ["Warna konversi tinggi", "Layout urgency", "Bisa animasi Canva"],
      priceOriginal: 15000,
      priceDiscount: 10000,
      image: "/promosi.png",
      popular: false,
    }
  ],
  webcode: [
    {
      title: "SaaS Landing Page Next.js",
      description: "Source code landing page modern dengan Tailwind CSS dan Framer Motion.",
      descriptionFull: "Source code lengkap SaaS landing page modern dengan React/Next.js, Tailwind CSS, Framer Motion, dan email handler ready. Siap dideploy ke Vercel atau Netlify.",
      features: ["Next.js App Router", "Tailwind CSS & Framer Motion", "SEO & Speed Optimized"],
      priceOriginal: 150000,
      priceDiscount: 99000,
      image: "/flyer.png",
      popular: true,
    },
    {
      title: "Aesthetic Portfolio Dev",
      description: "Template website portfolio minimalis untuk desainer dan developer.",
      descriptionFull: "Template portofolio minimalis dan estetik untuk memamerkan karya visual, riwayat proyek, dan kontak Anda. Dibuat dengan React & Tailwind CSS.",
      features: ["Aesthetic design", "Fully responsive", "Form kontak WA integrasi"],
      priceOriginal: 99000,
      priceDiscount: 49000,
      image: "/flyer.png",
      popular: false,
    },
    {
      title: "Dashboard Admin Template",
      description: "Template UI dashboard analitik lengkap dengan grafik.",
      descriptionFull: "Kumpulan komponen dashboard, tabel, dan chart interaktif yang dibangun menggunakan React dan Tailwind CSS. Cocok untuk back-office.",
      features: ["Komponen Reusable", "Dark Mode Ready", "Charts terintegrasi"],
      priceOriginal: 250000,
      priceDiscount: 149000,
      image: "/flyer.png",
      popular: true,
    },
    {
      title: "E-Commerce Storefront",
      description: "Source code katalog toko online siap pakai.",
      descriptionFull: "Website katalog produk lengkap dengan keranjang belanja, integrasi WhatsApp checkout, dan pencarian produk real-time.",
      features: ["Katalog dinamis", "WhatsApp Checkout", "Mobile friendly"],
      priceOriginal: 199000,
      priceDiscount: 129000,
      image: "/flyer.png",
      popular: false,
    }
  ],
  print: [
    {
      title: "Spanduk Warung Makan",
      description: "Template spanduk ukuran besar resolusi tinggi.",
      descriptionFull: "Desain spanduk warung atau UMKM yang menarik perhatian dari kejauhan. Warna cerah dan format siap cetak (CMYK).",
      features: ["Large format scale", "Print ready CMYK", "High visibility"],
      priceOriginal: 30000,
      priceDiscount: 20000,
      image: "/promosi.png",
      popular: false,
    },
    {
      title: "Brosur Lipat Tiga (Trifold)",
      description: "Template brosur perusahaan profesional.",
      descriptionFull: "Brosur trifold elegan untuk profil perusahaan, institusi sekolah, atau layanan jasa Anda.",
      features: ["Layout trifold rapi", "Ruang teks luas", "Elegan & Corporate"],
      priceOriginal: 45000,
      priceDiscount: 25000,
      image: "/flyer.png",
      popular: true,
    },
    {
      title: "Kartu Nama Minimalis",
      description: "Desain kartu nama estetik dan profesional.",
      descriptionFull: "Buat kesan pertama yang berkesan dengan desain kartu nama berkelas yang siap cetak dan mudah disesuaikan.",
      features: ["Desain dua sisi", "Minimalis modern", "QR Code Space"],
      priceOriginal: 15000,
      priceDiscount: 10000,
      image: "/promosi.png",
      popular: false,
    },
    {
      title: "Menu Kafe & Restoran",
      description: "Desain buku menu yang menggugah selera.",
      descriptionFull: "Tampilkan hidangan andalan kafe atau restoran Anda dengan layout menu yang bersih dan menarik.",
      features: ["Tipografi menu jelas", "Ruang foto makanan", "Bisa satu atau dua muka"],
      priceOriginal: 35000,
      priceDiscount: 25000,
      image: "/promosi.png",
      popular: false,
    }
  ]
}

export const faqs = [
  { q: "Apakah ada biaya tersembunyi?", a: "Sama sekali tidak. Harga template yang tertera pada paket sudah final dan sekali bayar." },
  { q: "Bagaimana cara mendapatkan template setelah membayar?", a: "Setelah melakukan konfirmasi transfer di halaman checkout, sistem kami akan segera mengirimkan tautan Canva / link project template ke email yang terdaftar." },
  { q: "Apakah template ini mudah diedit?", a: "Sangat mudah! Kami menyediakan link template Canva yang bisa Anda edit langsung di browser atau HP." }
]